name: barcelona-noise-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  # Core libraries
  - python=3.9
  - pandas>=2.0.0
  - numpy>=1.23.0
  - scikit-learn>=1.0.0
  - xgboost>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # Data processing
  - pyarrow>=6.0.0
  - pyspark>=3.1.0

  # Utilities
  - boto3>=1.26.0
  - sagemaker>=2.150.0

  # Testing and debugging
  - pytest>=7.0.0
  - ipykernel>=6.0.0

  # Herramientas adicionales
  - pip>=21.0.0
  - pip:
      - s3fs>=2023.1.0  # S3 access from pandas