channels:
- conda-forge
dependencies:
- python=3.9.21
- pip<=25.0
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
