# Paths for raw, processed, and external data
data:
  raw: "data/raw/"                     
  processed: "data/processed/"  
  external: "data/external/"           
  outputs: "data/outputs/"             

# Paths for trained models
models:
  production: "models/production/best_model.pkl"       
  experiments: "models/experiments/"                  

# Paths for reports and figures
reports:
  figures: "reports/figures/"                          
  final_report: "reports/presentations/final_report.pptx"  

# Paths for notebooks and source code
code:
  notebooks: "notebooks/"                            
  src: "src/"                                         